.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. btw_qt test_btw_qt
clean: FORCE
	$(MAKE) -C .. btw_qt_clean test_btw_qt_clean
check: FORCE
	$(MAKE) -C .. test_btw_qt_check
btw-qt btw-qt.exe: FORCE
	 $(MAKE) -C .. btw_qt
